[project]
name = "genai-practical-project-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.16"
dependencies = [
    "accelerate>=1.13.0",
    "diffusers[torch]>=0.37.1",
    "matplotlib>=3.10.9",
    "pandas<3",
    "pillow<12",
    "safetensors>=0.7.0",
    "transformers>=5.8.1",
]
